In [224]:
import pandas as pd
import numpy as np
from dateutil import parser

In [225]:
#create messy raw data
data = { 
    "EmpId": [101, 102, "103", 104, 105, 106, 107, 108, 109, 110],
    "fullName": [
        " Alice Johnson ", "MICHEAL smith", "sarah lee", "David-Kim", None, "john brown",
        "Emma Wilson", "TOM davis", "Jane Miller", "Chris taylor"
    ],
    "Dept": [
        "IT", "hr", "Mktng", "IT", "Customer Care", "marketing", "Finance", None, "HR", "marketing"],
    "Age": [29, "thirty-five", 26, 31, 42, 27, 33, 30, None, 28],
    "Salary($)": ["$5500.50", "4800", "4200.75", "NaN", "6100", "4,300", "5800", "5000", "4700.0", "4400"],
    "JoinDate" : [
        "12-04-2021" , "2020.11.01" , "Jan 18, 2022" , "2019/9/25" , "07/05/18" , "2021-10-14" ,
        "2019/12/01" , "2020-03-22" , "May 10th, 2021" , "2022-02-05"
    ], 
    "Performance": [87, "73", 90, 65, 82, 75, 88, None, "79%", "91"],
  "Remote?": ["Yes", "No", "Y", "N", "yes", "no", "Y", "Yes", None, "True"]
}

In [226]:
#create a dataframe
data_frame = pd .DataFrame(data)

#convert dataframe into csv file
data_frame.to_csv("data/employee_dataset.csv", index=False)

#load dataset
df = pd.read_csv("data/employee_dataset.csv")

df

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [227]:
#check the info of the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmpId        10 non-null     int64
 1   fullName     9 non-null      str
 2   Dept         9 non-null      str
 3   Age          9 non-null      str
 4   Salary($)    9 non-null      str
 5   JoinDate     10 non-null     str
 6   Performance  9 non-null      str
 7   Remote?      9 non-null      str
dtypes: int64(1), str(7)
memory usage: 772.0 bytes

In [228]:
#get the dataset shape
df.shape

(10, 8)

In [229]:
#get the first five rows
df.head(6)

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no

In [230]:
#get the dataset columns
df.columns

Index(['EmpId', 'fullName', 'Dept', 'Age', 'Salary($)', 'JoinDate',
       'Performance', 'Remote?'],
      dtype='str')

In [231]:
#check missing values
df.isnull().sum()

EmpId          0
fullName       1
Dept           1
Age            1
Salary($)      1
JoinDate       0
Performance    1
Remote?        1
dtype: int64

In [232]:
#inspect unique values in columns

print(df['Dept'].unique())
print(df['Age'].unique())
print(df['Remote?'].unique())

<StringArray>
['IT', 'hr', 'Mktng', 'Customer Care', 'marketing', 'Finance', nan, 'HR']
Length: 8, dtype: str
<StringArray>
['29', 'thirty-five', '26', '31', '42', '27', '33', '30', nan, '28']
Length: 10, dtype: str
<StringArray>
['Yes', 'No', 'Y', 'N', 'yes', 'no', nan, 'True']
Length: 8, dtype: str

In [233]:
#access salary value
df['Salary($)'].to_list()

['$5500.50',
 '4800',
 '4200.75',
 nan,
 '6100',
 '4,300',
 '5800',
 '5000',
 '4700.0',
 '4400']

In [234]:
df['Salary($)'].head()

0    $5500.50
1        4800
2     4200.75
3         NaN
4        6100
Name: Salary($), dtype: str

In [235]:
#start cleaning inconsistent values
#clean columns name
df.rename(columns={
    "EmpId": "emp_id",
    "fullName": "full_name",
    "Dept": "department",
    "Age": "age",
    "Salary($)": "salary",
    "JoinDate": "join_date",
    "Performance": "performance",
    "Remote?": "remote"
}, inplace=True)

df

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [236]:
#clean inconsistence values on full_name


#let check for the values we have on fullname
df['full_name'].to_list()

[' Alice Johnson ',
 'MICHEAL smith',
 'sarah lee',
 'David-Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM davis',
 'Jane Miller',
 'Chris taylor']

In [237]:
df['full_name'] = (
    df['full_name'] 
    .str.strip()
    .str.title()
    .str.replace(r"[\s-]+", " ", regex=True)
)

df['full_name'].to_list()

['Alice Johnson',
 'Micheal Smith',
 'Sarah Lee',
 'David Kim',
 nan,
 'John Brown',
 'Emma Wilson',
 'Tom Davis',
 'Jane Miller',
 'Chris Taylor']

In [238]:
#clean inconsistence values in department
df.replace({
    "hr": "HR",
    "Mktng": "Marketing",
    "marketing": "Marketing",

}, inplace=True)

df['department']

0               IT
1               HR
2        Marketing
3               IT
4    Customer Care
5        Marketing
6          Finance
7              NaN
8               HR
9        Marketing
Name: department, dtype: str

In [239]:
#check the vales of age
df['age'].to_list()

['29', 'thirty-five', '26', '31', '42', '27', '33', '30', nan, '28']

In [240]:
#clean inconsistence value in age
def clean_age(value):
   if value == "thirty-five":
       return 35
   elif isinstance(value, (int, float)):
       return value
   elif isinstance (value, str) and value.isdigit():
        return int(value)
   else:
        return np.nan

df['age'] = df['age'].apply(clean_age)

df['age']

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8     NaN
9    28.0
Name: age, dtype: float64

In [241]:
#check the values of salary
df['salary'].head

<bound method NDFrame.head of 0    $5500.50
1        4800
2     4200.75
3         NaN
4        6100
5       4,300
6        5800
7        5000
8      4700.0
9        4400
Name: salary, dtype: str>

In [242]:
#cleaning the values and convert it from string to float
df['salary'] =(
    df['salary']
    .astype(str)
    .replace(r"[$,]", "", regex=True)
    .replace("NaN", np.nan)
    .astype(float)
)

df["salary"]

0    5500.50
1    4800.00
2    4200.75
3        NaN
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: salary, dtype: float64

In [243]:
df['performance'] = (
    df['performance']
    .astype(str)
    .replace(r"[%]", "", regex=True)
    .replace("None", np.nan)
    .astype(float)
)
    
df['performance']

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7     NaN
8    79.0
9    91.0
Name: performance, dtype: float64

In [244]:
#clean the inconsistency value in remote
df.replace({
    "yes": "Yes",
    "no": "No",
    "N": "No",
    "Y": "Yes",
    "None": np.nan,
    "True": "Yes"
}, inplace=True)

df

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.50,12-04-2021,87.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020.11.01,73.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,"Jan 18, 2022",90.0,Yes
3,104,David Kim,IT,31.0,NaN,2019/9/25,65.0,No
4,105,NaN,Customer Care,42.0,6100.00,07/05/18,82.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
6,107,Emma Wilson,Finance,33.0,5800.00,2019/12/01,88.0,Yes
7,108,Tom Davis,NaN,30.0,5000.00,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.00,"May 10th, 2021",79.0,NaN
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes

In [245]:
#clean inconsistence value in join_date colomn
df['join_date'].to_list()

['12-04-2021',
 '2020.11.01',
 'Jan 18, 2022',
 '2019/9/25',
 '07/05/18',
 '2021-10-14',
 '2019/12/01',
 '2020-03-22',
 'May 10th, 2021',
 '2022-02-05']

In [246]:
#df['join_date'] = pd.to_datetime(df['join_date'], errors="coerce")
#df['join_date']

def date_parser(date_str):
    try:
        return parser.parse(date_str, dayfirst=True)
    except Exception:
        return pd. NaT

df['join_date'] = df['join_date'].apply(date_parser)
df['join_date']

0   2021-04-12
1   2020-01-11
2   2022-01-18
3   2019-09-25
4   2018-05-07
5   2021-10-14
6   2019-01-12
7   2020-03-22
8   2021-05-10
9   2022-05-02
Name: join_date, dtype: datetime64[us]

In [247]:
#clean inconsistence values in employee id
df['emp_id'] = pd.to_numeric(df['emp_id'], errors='coerce')
df['emp_id']

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: emp_id, dtype: int64

In [248]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   emp_id       10 non-null     int64
 1   full_name    9 non-null      str
 2   department   9 non-null      str
 3   age          9 non-null      float64
 4   salary       9 non-null      float64
 5   join_date    10 non-null     datetime64[us]
 6   performance  9 non-null      float64
 7   remote       9 non-null      str
dtypes: datetime64[us](1), float64(3), int64(1), str(3)
memory usage: 772.0 bytes

In [249]:
#handling missing values
df['full_name'] = df['full_name'].fillna("Unknown")
df['full_name']

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4          Unknown
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: full_name, dtype: str

In [250]:
df['department'] = df['department'].fillna(df['department'].mode()[0])
df['department']

0               IT
1               HR
2        Marketing
3               IT
4    Customer Care
5        Marketing
6          Finance
7        Marketing
8               HR
9        Marketing
Name: department, dtype: str

In [251]:
df['age'] = df['age'].fillna(df['age'].median())
df['age']

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8    30.0
9    28.0
Name: age, dtype: float64

In [253]:
df['salary'] = df['salary'].fillna(df['salary'].median())
df['salary']

0    5500.50
1    4800.00
2    4200.75
3    4800.00
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: salary, dtype: float64

In [256]:
df['performance'] = df['performance'].fillna(df['performance'].median())
df['performance']

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7    82.0
8    79.0
9    91.0
Name: performance, dtype: float64

In [257]:
df['remote'] = df['remote'].fillna(df['remote'].mode()[0])
df['remote']

0    Yes
1     No
2    Yes
3     No
4    Yes
5     No
6    Yes
7    Yes
8    Yes
9    Yes
Name: remote, dtype: str

In [259]:
#working with filtering
df['full_name']

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4          Unknown
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: full_name, dtype: str

In [260]:
df.head()

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
1,102,Micheal Smith,HR,35.0,4800.00,2020-01-11,73.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
4,105,Unknown,Customer Care,42.0,6100.00,2018-05-07,82.0,Yes

In [261]:
df[['full_name', 'salary', 'performance']]

       full_name   salary  performance
0  Alice Johnson  5500.50         87.0
1  Micheal Smith  4800.00         73.0
2      Sarah Lee  4200.75         90.0
3      David Kim  4800.00         65.0
4        Unknown  6100.00         82.0
5     John Brown  4300.00         75.0
6    Emma Wilson  5800.00         88.0
7      Tom Davis  5000.00         82.0
8    Jane Miller  4700.00         79.0
9   Chris Taylor  4400.00         91.0

In [262]:
df.iloc[0:3, 0:3]

   emp_id      full_name department
0     101  Alice Johnson         IT
1     102  Micheal Smith         HR
2     103      Sarah Lee  Marketing

In [264]:
df.loc[df['salary'] >= 5000]

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes
4,105,Unknown,Customer Care,42.0,6100.0,2018-05-07,82.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.0,2019-01-12,88.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.0,2020-03-22,82.0,Yes